# [Python Reference Link](http://www.data8.org/sp20/python-reference.html)
*Run the cell below so that we can set our modules up*

In [35]:
import numpy as np
from datascience import *

In [36]:
# These lines set up graphing capabilities.
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import warnings
warnings.simplefilter('ignore', FutureWarning)

from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

# Comparison Expressions and Operations

In [37]:
2 > 3

False

In [38]:
# assigning the integer 4 to the variable 'x' and then checking to see if it's greater than 3
x = 4
x >= 3

True

In [39]:
# assigning the integer 7 to the variable 'y' and then checking to compare the numbers stored in 'x' vs. 'y'
y = 7
x <= y

True

In [40]:
# Does 'x' equal 'y'?
x == y

False

In [41]:
#
c = x*3
c == 6

False

In [42]:
#
x != 3

True

In [43]:
#
x < c < y

False

# Aggregating Comparisons

In [44]:
#
this = make_array(1,2,3,4,5,6,7,8)
this >= 5

array([False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [45]:
#
drinks = make_array('Coffee','Latte','Mocha','Coffee','Frappacino')

In [46]:
#
drinks == 'Coffee'

array([ True, False, False,  True, False], dtype=bool)

In [47]:
#
sum(drinks == 'Coffee')

2

# Practice with `Spotify`

About `spotify` 

One of the biggest music streaming platform, but who's the biggest streamed here? This dataset which is webscrapped and accumulated all the stream metrics of each artist and their respective songs.<br>

Position - Spotify Ranking <br>
Artist Name - Artist Name <br>
Song Name - Song Name <br>
Days - No of days since the release of the song (Updated) <br>
Top 10 (xTimes) - No of times inside top 10 <br>
Peak Position - Peak position attained <br>
Peak Position (xTimes) - No of times Peak position attained <br>
Peak Streams - Total no of streams during Peak position <br>
**Total Streams ** - Total song streams

In [48]:
spotify = Table.read_table('Spotify_final_dataset.csv')
spotify

Position | Artist Name   | Song Name                                  | Days | Top 10 (xTimes) | Peak Position | Peak Position (xTimes) | Peak Streams | Total Streams
1        | Post Malone   | Sunflower  SpiderMan: Into the SpiderVerse | 1506 | 302             | 1             | (x29)                  | 2118242      | 883369738
2        | Juice WRLD    | Lucid Dreams                               | 1673 | 178             | 1             | (x20)                  | 2127668      | 864832399
3        | Lil Uzi Vert  | XO TOUR Llif3                              | 1853 | 212             | 1             | (x4)                   | 1660502      | 781153024
4        | J. Cole       | No Role Modelz                             | 2547 | 6               | 7             | 0                      | 659366       | 734857487
5        | Post Malone   | rockstar                                   | 1223 | 186             | 1             | (x124)                 | 2905678      | 718865961
6        | Travis Scott  | goosebumps                                 | 1995 | 4               | 8             | 0                      | 977275       | 672972704
7        | The Weeknd    | Blinding Lights                            | 1100 | 233             | 1             | (x11)                  | 2355059      | 644287953
8        | XXXTENTACION  | Jocelyn Flores                             | 1673 | 44              | 2             | (x1)                   | 3175206      | 624457164
9        | XXXTENTACION  | SAD!                                       | 1217 | 133             | 1             | (x6)                   | 4437612      | 619879245
10       | Juice WRLD    | All Girls Are The Same                     | 1681 | 2               | 5             | 0                      | 1239152      | 613872384
... (11074 rows omitted)

## Practice question: 

#### In the cell above, we saved a data table of Spotify Top 10000 streamed songs. Let's load the cell below with an array containing the peak position of each song.

In [49]:
peak_position = spotify.column('Peak Position')
peak_position

array([  1,   1,   1, ..., 167, 200, 184])

#### Let's construct an array that tells us whether each song reached the #1 peak position.

In [50]:
no_1_peak = (peak_position == 1)
no_1_peak

array([ True,  True,  True, ..., False, False, False], dtype=bool)

#### Now use the sum function to determine the number of songs in this dataset which peaked at #1. 

In [51]:
sum(no_1_peak)

190

#### This line of thinking is *very similar* to a method we have gotten quite familiar with recently. Use that method to verify our solution we just found.

In [52]:
spotify.where('Peak Position',are.equal_to(1)).num_rows

190

# Control Statements 'If'

In [53]:
x = 20
s = 'You are 20'

In [54]:
if x >= 18:
    s = 'You can legally vote'
s

'You can legally vote'

In [55]:
if x >= 21: 
    s = 'You may enter this bar/nightclub'
s 

'You can legally vote'

In [56]:
x = 25 

In [57]:
if x >= 21: 
    s = 'You may enter this bar/nightclub'
s 

'You may enter this bar/nightclub'

In [58]:
def age(input_age):
    if input_age >= 18:
        return 'You can legally vote'
    if input_age >= 21:
        return 'You can legally drink'

In [63]:
age(25)

'You can legally drink'

In [64]:
age(20)

'You can legally vote'

In [65]:
age(3)

'You can legally drink milk'

awkward.... Let's fix the age function below:

In [62]:
def age(input_age):
    if input_age >= 21:
        return 'You can legally drink'
    elif input_age >= 18: #this only gets checked if the 'if' condition above is false
        return 'You can legally vote'
    else: #only runs if all the if/elif conditions above were false
        return 'You can legally drink milk'

# Control Statements 'for' a.k.a. the 'for'-loop

In [66]:
for pet in make_array('cat','dog','rabbit','ferret'):
    print('I love my '+ pet)

I love my cat
I love my dog
I love my rabbit
I love my ferret


In [67]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


#### Exercise:
Let's use a for-loop to code for a song that is **extremely** repetitive: "99 bottles of Beer"...

In [88]:
for beer_num in np.arange(99,0,-1):
    print(beer_num,"bottles of beer on the wall,",beer_num,"bottles of beer!")
    print("take one down, pass it around!",beer_num-1,"bottles of beer on the wall!")

99 bottles of beer on the wall, 99 bottles of beer!
take one down, pass it around! 98 bottles of beer on the wall!
98 bottles of beer on the wall, 98 bottles of beer!
take one down, pass it around! 97 bottles of beer on the wall!
97 bottles of beer on the wall, 97 bottles of beer!
take one down, pass it around! 96 bottles of beer on the wall!
96 bottles of beer on the wall, 96 bottles of beer!
take one down, pass it around! 95 bottles of beer on the wall!
95 bottles of beer on the wall, 95 bottles of beer!
take one down, pass it around! 94 bottles of beer on the wall!
94 bottles of beer on the wall, 94 bottles of beer!
take one down, pass it around! 93 bottles of beer on the wall!
93 bottles of beer on the wall, 93 bottles of beer!
take one down, pass it around! 92 bottles of beer on the wall!
92 bottles of beer on the wall, 92 bottles of beer!
take one down, pass it around! 91 bottles of beer on the wall!
91 bottles of beer on the wall, 91 bottles of beer!
take one down, pass it aroun

#### Exercise:
Consider the following string:

In [68]:
STEM_Center_Webpage_string = 'The Skyline College STEM Center brings together academic and student support services for students taking science, technology, engineering and math courses.The center supports student success by ensuring students have access to resources such as academic tutoring, counseling services, a resource depository for STEM pathways and transfer, a hub for internships and work based learning opportunities, as well as a place where students and staff can collaborate and build a community and supportive connection. This STEM Center was brought to campus by a U.S. Department of Education, Title V, Developing Hispanic-Serving Institutions Program “Strengthening Pathways to Success in STEM” grant awarded in 2018.'
STEM_Center_Webpage_string

'The Skyline College STEM Center brings together academic and student support services for students taking science, technology, engineering and math courses.The center supports student success by ensuring students have access to resources such as academic tutoring, counseling services, a resource depository for STEM pathways and transfer, a hub for internships and work based learning opportunities, as well as a place where students and staff can collaborate and build a community and supportive connection. This STEM Center was brought to campus by a U.S. Department of Education, Title V, Developing Hispanic-Serving Institutions Program “Strengthening Pathways to Success in STEM” grant awarded in 2018.'

We'll use the `.split()` method to store each word into a list:

In [83]:
STEM_split = STEM_Center_Webpage_string.split()
#STEM_split

Now, use a for-loop to check the list to see how many times 'student' is mentioned on the webpage

In [84]:
STEM_split == 'student'
type(STEM_split)
#sum(STEM_split=='student')

list

In [86]:
student_count = 0 
for word in STEM_split:
    #print(word)
    if word == 'student':
        print('Found!'+word)
        student_count = student_count +1

        
student_count

2

# Saved for Thursday (10/19)

# Random Selection

## 'np.random.choice' will help us produce arrays that are randomly generated
Consider the array of food we could get at the Sky Cafe here on campus: 

In [ ]:
cafe_lunch_options = make_array('Salad Bar','Chicken Tendies','Quesadilla','Burger','Just hella fries',
                                'Daily Special','Sandwich','Cup Noodle')
cafe_lunch_options

#### I forgot to bring my lunch from home today, what am I getting? Run the cell below:

In [ ]:
np.random.choice(cafe_lunch_options)

#### Allison also forgot hers. She said, "I don't know, surprise me." What are we each getting?

## Appending items to arrays and other arrays to arrays

## 'tbl.sample' will help produce smaller tables that are randomly generated