# [Python Reference Link](http://www.data8.org/sp20/python-reference.html)
*Run the cell below so that we can set our modules up*

In [1]:
#Setting up the demo notebook
import otter
grader = otter.Notebook("lab01.ipynb")
from datascience import *
import numpy as np

# Demo Request: 5.1.1 from [Lab01](https://skyline.cloudbank.2i2c.cloud/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fb00chan%2Fmath211_fall23_skyline&urlpath=tree%2Fmath211_fall23_skyline%2Flab%2Flab01%2Flab01.ipynb&branch=main)

Ok, your turn. 

**Question 5.1.1.** Given the lengths of Yanay's cats Hummus, Gatkes, and Zeepty, write an expression that computes the smallest difference between any of the three lengths. Your expression shouldn't have any numbers in it, only function calls and the names `hummus`, `gatkes`, and `zeepty`. Give the value of your expression the name `min_length_difference`.


In [19]:
# The three cats' lengths, in meters:
hummus =  24.5 # Hummus is 24.5 inches long
gatkes = 19.7 # Gatkes is 19.7 inches long
zeepty = 15.8 # Zeepty is 15.8 inches long
             
# We'd like to look at all 3 pairs of lengths, 
# compute the absolute difference between each pair, 
# and then find the smallest of those 3 absolute differences.  
# This is left to you!  
# If you're stuck, try computing the value for each step of the process 
# (like the difference between Hummus's length and Gatkes's length) 
# on a separate line and giving it a name (like hummus_gatkes_length_diff)
min_length_difference = min(abs(gatkes - hummus),abs(gatkes - zeepty),abs(zeepty - hummus))
min_length_difference

3.8999999999999986

In [12]:
gatkes_hummus_length_diff = abs(gatkes - hummus)
gatkes_hummus_length_diff

4.800000000000001

In [13]:
abs(gatkes - zeepty)

3.8999999999999986

In [14]:
abs(zeepty - hummus)

8.7

In [16]:
grader.check("q5_1_1")

q5_1_1 results: All test cases passed!

In [ ]:
round(5,1)

# Arrays  

In [30]:
tester = make_array(1,2,3,4,5)
tester

array([1, 2, 3, 4, 5])

In [23]:
len?

In [31]:
tester = tester+5
print(tester)
tester = tester+5
print(tester)
tester = tester+5

print(tester)
print(len(tester))
type(len(tester))

[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
5


int

In [32]:
tester*10

array([160, 170, 180, 190, 200])

In [34]:
sum(tester)

90

In [35]:
16+17+18+19+20

90

In [37]:
np.average(tester)

18.0

# Columns of Tables are Arrays

In [38]:
math211_survey = Table.read_table('Math211_FallSurvey.csv')
math211_survey

Timestamp       | Surveyor     | GPA  | introversion/extroversion | Pets                 | Handed       | Sleep Position | K-Pop | K-Pop Group | travel destination | Birthplace                | Transfer destination | Fear                                   | Music Genre | Color
8/17/2023 16:33 | Christian Le | 2.86 | 6                         | Dogs                 | Right-handed | On my side     | Yes   | Le Sserafim | Japan              | Local                     | UC                   | Working                                | Pop         | Red
8/17/2023 16:34 | Christian Le | 4    | 8                         | nan                  | Right-handed | On my back     | Yes   | Le Sserafim | Switzerland        | Local                     | UC                   | A regretful life                       | All         | Black
8/17/2023 16:38 | Christian Le | 2.5  | 8                         | Cats                 | Right-handed | On my stomach  | Yes   | Seventeen   | Hawaii             | Local                     | UC Transfer          | Death, Spiders                         | R&B, K-POP  | Green
8/17/2023 16:38 | Christian Le | 3.96 | 6                         | Cats                 | Right-handed | On my side     | Yes   | STAYC       | Costa Rica         | Local                     | UC Grad              | Loss of loved ones                     | R&B, K-POP  | Purple
8/17/2023 16:54 | Christian Le | 2.98 | 6                         | nan                  | Left-handed  | On my side     | Yes   | New Jeans   | Hawaii             | Local                     | nan                  | Death                                  | R&B         | Green
8/17/2023 16:55 | Christian Le | 3.8  | 8                         | Dogs                 | Right-handed | On my side     | Yes   | New Jeans   | Hawaii             | Local                     | UC                   | Being alone                            | R&B         | Blue
8/17/2023 17:00 | Christian Le | 4    | 3                         | nan                  | Right-handed | On my back     | No    | nan         | Japan              | California (not Bay Area) | CSU                  | Not being accepted into career program | Hip hop     | Khaki
8/17/2023 18:13 | Christian Le | 4    | 2                         | Cats, Dogs, Reptiles | Both         | On my stomach  | Yes   | New Jeans   | Dubai              | Local                     | UC                   | Insects                                | Pop         | Red
8/17/2023 20:38 | Casey So     | 3.86 | 3                         | Dogs                 | Right-handed | On my back     | Yes   | Seventeen   | Korea              | Local                     | UC                   | Birds                                  | Pop         | Light Blue
8/17/2023 20:43 | Casey So     | 3.2  | 4                         | nan                  | Right-handed | On my side     | Yes   | Twice       | Philippines        | Local                     | UC                   | Death                                  | Pop         | Blue
... (223 rows omitted)

In [58]:
# pulling out the GPA column as an array 
gpa_col = math211_survey.column('GPA')
len(gpa_col)

233

In [59]:
fixed_gpa_col = math211_survey.where('GPA',are.below(10)).column('GPA')
np.average(fixed_gpa_col)

3.5450732758620691

In [40]:
type(gpa_col)

numpy.ndarray

In [42]:
np.average(gpa_col)

3.9075407725321893

# np.arange

In [43]:
import numpy as np
#np.arange(stop)
#np.arange(*start,stop)
#np.arange(*start,stop,*step)

In [44]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [45]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [46]:
np.arange(2,102,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [48]:
np.arange?

# Building Tables

In [50]:
subscription = make_array('Netflix','Max','Hulu','Crunchyroll','Spotify','DoorDash','AmazonPrime','Discord Nitro')
subscription

array(['Netflix', 'Max', 'Hulu', 'Crunchyroll', 'Spotify', 'DoorDash',
       'AmazonPrime', 'Discord Nitro'],
      dtype='<U13')

In [51]:
#Amazon and Discord are annual fees
month_fee_cost = make_array(19.99,14.99,9.99,9.99,9.99,9.99,(130/12),(169.97/12))
month_fee_cost

array([ 19.99      ,  14.99      ,   9.99      ,   9.99      ,
         9.99      ,   9.99      ,  10.83333333,  14.16416667])

In [52]:
bryans_monthly_subscriptions = Table().with_columns('Subscription',subscription,'$$ per month',month_fee_cost)
bryans_monthly_subscriptions

Subscription  | $$ per month
Netflix       | 19.99
Max           | 14.99
Hulu          | 9.99
Crunchyroll   | 9.99
Spotify       | 9.99
DoorDash      | 9.99
AmazonPrime   | 10.8333
Discord Nitro | 14.1642

In [53]:
annual_cost = bryans_monthly_subscriptions.column('$$ per month') * 12
annual_cost

array([ 239.88,  179.88,  119.88,  119.88,  119.88,  119.88,  130.  ,
        169.97])

In [55]:
new_table = bryans_monthly_subscriptions.with_column('$$ each year',annual_cost).drop('$$ per month')
new_table

Subscription  | $$ each year
Netflix       | 239.88
Max           | 179.88
Hulu          | 119.88
Crunchyroll   | 119.88
Spotify       | 119.88
DoorDash      | 119.88
AmazonPrime   | 130
Discord Nitro | 169.97